[package]
name = "rs-utils-def"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "serialk-watcher"
path = "serialk-watcher.rs"

[dependencies]
tensorflow = "0.21.0"
notify = "5.1.0"
clap = { version = "4.3", features = ["derive"] }
git2 = "0.18"
log = "0.4"
env_logger = "0.10"
